theme = "congo"

baseURL = "https://elmassas.com/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  custom_css = "custom.css" 
