languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "ElMassas"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["posts", "tags"]
  description = "Miguel Luis personal website"

[params.author]
  name = "Miguel Luis"
  image = "img/avatar.png"
  headline = "Tech guy that likes other topics"
  bio = "DevSecOps Engineer"
  links = [
  { gitlab = "https://gitlab.com/ElMassas" },
  { instagram = "https://instagram.com/el.massas" },
  { linkedin = "https://www.linkedin.com/in/miguel-filipe-lu%C3%ADs/" },
  { twitch = "https://www.twitch.tv/elmassastv" },
  { tiktok = "https://www.tiktok.com/@ElMassonas" },
  { youtube = "https://www.youtube.com/@el_massas" },
  { mal = "https://myanimelist.net/profile/elmassas" },
  { bluesky = "https://bsky.app/profile/elmassas.bsky.social" },
  { ko-fi = "https://ko-fi.com/elmassas" },
  { email = "mailto:misc@elmassas.com" }
  ]