[[main]]
  name = "About"
  url = "/about/"
  weight = 10

[[main]]
  name = "Blog"
  url = "/posts/"
  weight = 20

[[main]]
  name = "Categories"
  url = "/tags"
  weight = 30

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
